### ISSUE TITLE
Build from source using flatpak-builder-tools

### ISSUE THREAD

**Issue by julianrichen** [flathub/io.lbry.lbry-app#5]
It would be nice to build lbry-app from source using [flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools)'s yarn builder.

~Not working [WIP](julianrichen/io.lbry.lbry-app/tree/wip/flatpak-builder-tools).~

WIP at [wip/build-from-source](https://github.com/flathub/io.lbry.lbry-app/tree/wip/build-from-source)

**Comment by nedrichards** [comment]
Yeah - that'd be cool.

**Comment by julianrichen** [comment]
@nedrichards have you dealt with pre-built node modules before with other flathub apps? I don't know why but the `keytar` package insists on re-downloading a pre-build package which was already downloaded from `generated-sources.json`. It says the npm cache doesn't exists when it's been set as a ENV variable. I've never really built/developed a node.js app from source so this uncharted territory for me :/

WIP at [wip/build-from-source](https://github.com/flathub/io.lbry.lbry-app/tree/wip/build-from-source)

```
$ flatpak-builder --ccache --keep-build-dirs --force-clean --repo=lbry-repo lbry-app io.lbry.lbry-app.json
Emptying app dir 'lbry-app'
Downloading sources
Starting build of io.lbry.lbry-app
Cache hit for libsecret, skipping build
Cache hit for libnotify, skipping build
Cache hit for nodejs, skipping build
Cache hit for yarn, skipping build
Cache miss, checking out last cache hit
========================================================================
Building module lbry-app in /home/julian/Projects/io.lbry.lbry-app/.flatpak-builder/build/lbry-app-4
========================================================================
Running: yarn cache clean --offline
yarn cache v1.3.2
success Cleared cache.
Done in 0.02s.
Running: yarn install --offline --cwd /run/build/lbry-app/main
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.2.0: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.8.1: The platform "linux" is incompatible with this module.
info "app-builder-bin-mac@1.8.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-win@1.8.1: The platform "linux" is incompatible with this module.
info "app-builder-bin-win@1.8.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.7.2: The platform "linux" is incompatible with this module.
info "app-builder-bin-mac@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-win@1.7.2: The platform "linux" is incompatible with this module.
info "app-builder-bin-win@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/6] ⠂ keytar-prebuild: node@8.9.2 | linux | x64
[6/6] ⠂ node-sass:       npm config set proxy http://example.com:8080
[3/6] ⠂ electron
[-/6] ⠂ waiting...
error /run/build/lbry-app/main/node_modules/keytar-prebuild: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /run/build/lbry-app/main/node_modules/keytar-prebuild
Output:
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-prebuild-v4.0.4-node-v57-linux-x64.tar.gz
prebuild-install info npm cache directory missing, creating it... 
prebuild-install info looking for cached prebuild @ /home/julian/.npm/_prebuilds/https-github.com-electron-userland-electron-builder-binaries-releases-download-v4.0.4-keytar-prebuild-v4.0.4-node-v57-linux-x64.tar.gz
prebuild-install http request GET https://github.com/electron-userland/electron-builder-binaries/releases/download/v4.0.4/keytar-prebuild-v4.0.4-node-v57-linux-x64.tar.gz
prebuild-install WARN install getaddrinfo EAI_AGAIN github.com:443
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.2 | linux | x64
gyp http GET https://nodejs.org/download/release/v8.9.2/node-v8.9.2-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_AGAIN nodejs.org:443
gyp ERR! stack     at Object._errnoException (util.js:1024:11)
gyp ERR! stack     at errnoException (dns.js:55:15)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
gyp ERR! System Linux 4.16.7-300.fc28.x86_64
gyp ERR! command "/app/bin/node" "/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /run/build/lbry-app/main/node_modules/keytar-prebuild




Error: module lbry-app: Child process exited with code 1
```

**Comment by TingPing** [comment]
I've experienced the same failure on other projects, `node-gyp` just seems broken offline.

**Comment by julianrichen** [comment]
Thanks @TingPing I found [nodejs/node-gyp/issues/665](https://github.com/nodejs/node-gyp/issues/665) & [nodejs/node-gyp/issues/1191#issuecomment-301243919](https://github.com/nodejs/node-gyp/issues/1191#issuecomment-301243919) which seem to offer a hacky solution.

I downloaded the node.js headers to `$BUILDDIR/node-js-headers` and pointed the `npm_config_nodedir` environment variable to the same path and now `node-gyp` doesn't complain about missing headers and builds so more packages.

New archive:
```
{
    "type": "archive",
    "url": "https://nodejs.org/download/release/v8.9.2/node-v8.9.2-headers.tar.gz",
    "sha256": "35ac226795678ef2b9a8f55c3eb65984bb49f71858e771c9719452d14926e83e",
    "dest": "node-js-headers"
}
```
ENV:
```
"build-options" : {
    "env": {
        "electron_config_cache": "/run/build/lbry-app/electron-cache",
        "npm_config_nodedir": "/run/build/lbry-app/node-js-headers"
    }
}
```

Still more issues, lbry uses `electron-builder` which doesn't seem to get the `--offline` flag from `yarn` by default, so I guess I need to figure that out... Node.js really wasn't designed to be build offline -_-

```
========================================================================
Building module lbry-app in /home/julian/Projects/io.lbry.lbry-app/.flatpak-builder/build/lbry-app-5
========================================================================
Running: yarn cache clean --offline
yarn cache v1.3.2
success Cleared cache.
Done in 0.03s.
Running: yarn install --offline --cwd /run/build/lbry-app/main
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.2.0: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.8.1: The platform "linux" is incompatible with this module.
info "app-builder-bin-mac@1.8.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-win@1.8.1: The platform "linux" is incompatible with this module.
info "app-builder-bin-win@1.8.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-mac@1.7.2: The platform "linux" is incompatible with this module.
info "app-builder-bin-mac@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info app-builder-bin-win@1.7.2: The platform "linux" is incompatible with this module.
info "app-builder-bin-win@1.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ electron-builder install-app-deps && node build/downloadDaemon.js
  • electron-builder version=20.7.1
  • loaded configuration file=/run/build/lbry-app/main/electron-builder.json
  • loaded parent configuration file=/run/build/lbry-app/main/node_modules/electron-webpack/electron-builder.yml
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=keytar-prebuild
Error: /app/bin/node exited with code 1
Error output:
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds/keytar-prebuild-v4.0.4-electron-v54-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/julian/.npm/_prebuilds/https-github.com-electron-userland-electron-builder-binaries-releases-download-v4.0.4-keytar-prebuild-v4.0.4-electron-v54-linux-x64.tar.gz
prebuild-install http request GET https://github.com/electron-userland/electron-builder-binaries/releases/download/v4.0.4/keytar-prebuild-v4.0.4-electron-v54-linux-x64.tar.gz
prebuild-install WARN install getaddrinfo EAI_AGAIN github.com:443
sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.9.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/app/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/run/build/lbry-app/main/node_modules/keytar-prebuild/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/run/build/lbry-app/node-js-headers/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/run/build/lbry-app/node-js-headers',
gyp info spawn args   '-Dnode_gyp_dir=/app/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/run/build/lbry-app/node-js-headers/$(Configuration)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/run/build/lbry-app/main/node_modules/keytar-prebuild',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/app/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.16.7-300.fc28.x86_64
gyp ERR! command "/app/bin/node" "/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /run/build/lbry-app/main/node_modules/keytar-prebuild
gyp ERR! node -v v8.9.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (/run/build/lbry-app/main/node_modules/builder-util/src/util.ts:251:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at rebuild (/run/build/lbry-app/main/node_modules/electron-builder-lib/src/util/yarn.ts:149:27)
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: module lbry-app: Child process exited with code 1
```

**Comment by kcseb** [comment]
Thread seems abandoned. Closing.
